### ISSUE TITLE
update-bcd file path issues on Windows

### ISSUE THREAD

**Issue by hamishwillee** [openwebdocs/mdn-bcd-collector#328]
This is not a blocker - just letting you know. 

Got the following errors to do with absolute file paths on windows. Works on linux.

```
D:\github\mozilla\mdn-bcd-collector>npm run update-bcd -- -p api.RTCStatsReport*

> mdn-bcd-collector@9.0.2 update-bcd
> ts-node scripts/update-bcd.ts -p api.RTCStatsReport*

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at defer (D:\github\mozilla\mdn-bcd-collector\node_modules\ts-node\src\esm.ts:159:23)
    at entrypointFallback (D:\github\mozilla\mdn-bcd-collector\node_modules\ts-node\src\esm.ts:168:34)
    at D:\github\mozilla\mdn-bcd-collector\node_modules\ts-node\src\esm.ts:202:16
    at addShortCircuitFlag (D:\github\mozilla\mdn-bcd-collector\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (D:\github\mozilla\mdn-bcd-collector\node_modules\ts-node\src\esm.ts:197:12)
    at resolve (D:\github\mozilla\mdn-bcd-collector\node_modules\ts-node\src\child\child-loader.ts:15:39) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**Comment by queengooborg** [comment]
Windows is so wonderful, isn't it?  🙃

Would you be down to submit a pull request to fix this?  I don't use Windows so I can't test any patches!

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/19971 moved this script into BCD. @hamishwillee do you want to test if the problem persists there. Some dependencies had to be changed, so perhaps this was accidentally fixed by the move.

**Comment by hamishwillee** [comment]
@foolip So how do I test it in BCD ? - just `npm run update-bcd -- -p api.RTCStatsReport*` but from the BCD root?

**Comment by hamishwillee** [comment]
I'm going to close this because I haven't run into issues for ages!
