### ISSUE TITLE
Local server doesn't start without secrets.cookies defined

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/mdn-bcd-collector#949]
I think something was changed with session secrets. I don't see a discussion or a pull request about it unfortunately.

express-session deprecated req.secret; provide secret option file:/Users/florianscholz/dev/mdn-bcd-collector/app.js:113:9

Error: secret option required for sessions
    at session (/Users/florianscholz/dev/mdn-bcd-collector/node_modules/express-session/index.js:200:12)
    at Layer.handle [as handle_request] (/Users/florianscholz/dev/mdn-bcd-collector/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/florianscholz/dev/mdn-bcd-collector/node_modules/express/lib/router/index.js:328:13)
    at /Users/florianscholz/dev/mdn-bcd-collector/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/florianscholz/dev/mdn-bcd-collector/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/florianscholz/dev/mdn-bcd-collector/node_modules/express/lib/router/index.js:280:10)
    at cookieParser (/Users/florianscholz/dev/mdn-bcd-collector/node_modules/cookie-parser/index.js:57:14)
    at Layer.handle [as handle_request] (/Users/florianscholz/dev/mdn-bcd-collector/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/florianscholz/dev/mdn-bcd-collector/node_modules/express/lib/router/index.js:328:13)
    at /Users/florianscholz/dev/mdn-bcd-collector/node_modules/express/lib/router/index.js:286:9

**Comment by Elchi3** [comment]
I think the format of secrets.json changed. I was able to fix this by deleting secrets.json and regenerating it. Should `npm run clean` also remove secrets.json?

**Comment by queengooborg** [comment]
A new `cookies` secret was introduced in 18cc5359df83109530a692a0d0c434bff3439447, which switches our session ID logic from custom logic to an existing package.

Maybe using `secrets.sample.json` for defaults would be helpful?
